NetCoreIdentity/Controllers/MemberController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.FileProviders;
using NetCoreIdentity.Areas.Admin.Models;
using NetCoreIdentity.Extensions;
using NetCoreIdentity.Repository.Models;
using NetCoreIdentity.Core.ViewModels;
using System.Collections.Generic;
using System.Security.Claims;
using NetCoreIdentity.Core.Models;
using NetCoreIdentity.Service.Services;

namespace NetCoreIdentity.Controllers
{
    //[Authorize] this means only members can access these pages. You can use for only actionmethod or all controller it depends on your where you put this tag [Authorize]
    [Authorize]
    public class MemberController : Controller
    {
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;
        private readonly IFileProvider _fileProvider;
        private string userName => User.Identity!.Name!;    //=> means only get method
        private readonly IMemberService _memberService;
        public MemberController(SignInManager<AppUser> signInManager, UserManager<AppUser> userManager, IFileProvider fileProvider, IMemberService memberService)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _fileProvider = fileProvider;
            _memberService = memberService;
        }

        public async Task<IActionResult> Index()
        {
            //var userClaims = User.Claims.ToList();
            //var email = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Role);
            //var currentUser = await _userManager.FindByNameAsync(User.Identity!.Name!);
            //var userViewModel = new Core.ViewModels.UserViewModel
            //{
            //    UserName = currentUser.UserName,
            //    Email = currentUser.Email,
            //    PhoneNumber = currentUser.PhoneNumber,
            //    PictureUrl = currentUser.Picture
            //};
            return View(await _memberService.GetUserViewModelByUserName(userName));
        }

        //public async Task<IActionResult> Logout()
        //{
        //    await _signInManager.SignOutAsync();

        //    return RedirectToAction("Index", "Home");
        //}
        //alternative Logout method
        public async Task Logout()
        {
            await _memberService.Logout();
        }

        public IActionResult PasswordChange()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PasswordChange(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            //var currentUser = await _userManager.FindByNameAsync(User.Identity!.Name!);
            //var checkOldPassword = await _userManager.CheckPasswordAsync(currentUser, model.PasswordOld);
            if (!await _memberService.CheckPasswordAsync(userName, model.PasswordOld))
            {
                ModelState.AddModelError(string.Empty, "Incorrect old password!");
                return View();
            }
            //var resultChangePassword = await _userManager.ChangePasswordAsync(currentUser, model.PasswordOld, model.PasswordNew);
            var (isSuccess, errors) = await _memberService.ChangePasswordAsync(userName, model.PasswordOld, model.PasswordNew);
            if (!isSuccess)
            {
                ModelState.AddModelErrorList(errors!);
                return View();
            }
            //await _userManager.UpdateSecurityStampAsync(currentUser);
            //await _signInManager.SignOutAsync();
            //await _signInManager.PasswordSignInAsync(currentUser, model.PasswordNew, true, false);
            TempData["SuccessMessage"] = "Password has been change successfly.";

            return View();
        }

        public async Task<IActionResult> UserEdit()
        {
            ViewBag.GenderList = new SelectList(Enum.GetNames(typeof(EGender)));
            //var currentUser = await _userManager.FindByNameAsync(User.Identity!.Name!);
            //var userEditViewModel = new UserEditViewModel()
            //{
            //    UserName = currentUser.UserName,
            //    Email = currentUser.Email,
            //    PhoneNumber = currentUser.PhoneNumber,
            //    BirthDate = currentUser.BirthDate,
            //    City = currentUser.City,
            //    Gender = currentUser.Gender
            //};
            return View(await _memberService.GetUserEditViewModelAsync(userName));
        }

        [HttpPost]
        public async Task<IActionResult> UserEdit(UserEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var (isSuccess, errors) = await _memberService.EditUserAsync(model, userName);
            if (!isSuccess)
            {
                ModelState.AddModelErrorList(errors!);
                return View();
            }
            //var currentUser = await _userManager.FindByNameAsync(User.Identity!.Name!);
            //currentUser.UserName = model.UserName;
            //currentUser.Email = model.Email;
            //currentUser.PhoneNumber = model.PhoneNumber;
            //currentUser.BirthDate = model.BirthDate;
            //currentUser.City = model.City;
            //currentUser.Gender = model.Gender;
            //if (model.Picture != null && model.Picture.Length > 0)
            //{
            //    var wwwroot = _fileProvider.GetDirectoryContents("wwwroot");

            //    var randomFileName = $"{Guid.NewGuid().ToString()}{Path.GetExtension(model.Picture.FileName)}";

            //    var newPicturePath = Path.Combine(wwwroot.First(x => x.Name == "userPictures").PhysicalPath, randomFileName);

            //    using var stream = new FileStream(newPicturePath, FileMode.Create);
            //    await model.Picture.CopyToAsync(stream);

            //    currentUser.Picture = randomFileName;
            //}
            //var updateToUserResult = await _userManager.UpdateAsync(currentUser);

            //if (!updateToUserResult.Succeeded)
            //{
            //    ModelState.AddModelErrorList(updateToUserResult.Errors);
            //    return View();
            //}

            //await _userManager.UpdateSecurityStampAsync(currentUser);
            ////we need new cookie and we have to signout and signin again!
            //await _signInManager.SignOutAsync();
            //for claims
            //var claims = new List<Claim>();
            //if (model.BirthDate.HasValue)
            //{
            //    claims.Add(new Claim("Birthdate", model.BirthDate.Value.ToString()));
            //}
            //if (!String.IsNullOrEmpty(model.City))
            //{
            //    claims.Add(new Claim("City", model.City));
            //}
            //if (claims.Any())
            //{
            //    await _signInManager.SignInWithClaimsAsync(currentUser, true, claims.ToArray());
            //}
            //else
            //{
            //    // If there are no claims, you can use the regular SignInAsync
            //    await _signInManager.SignInAsync(currentUser,true);
            //}
            //else
            //{
            //    await _signInManager.SignInAsync(currentUser, true);
            //}

            //var userEditViewModel = new UserEditViewModel()
            //{
            //    UserName = currentUser.UserName,
            //    Email = currentUser.Email,
            //    PhoneNumber = currentUser.PhoneNumber,
            //    BirthDate = currentUser.BirthDate,
            //    City = currentUser.City,
            //    Gender = currentUser.Gender
            //};
            TempData["SuccessMessage"] = "User information has been changed successfly.";
            return View(await _memberService.GetUserEditViewModelAsync(userName));

        }

        public IActionResult AccessDenied(string returnUrl)
        {
            string message = string.Empty;
            message = "You are not authorized to view this page! Sorry, not sorry dudeee.";
            ViewBag.message = message;
            return View();
        }

        [HttpGet]
        public  IActionResult Claims()
        {
            var userClaimList = User.Claims.Select(x => new ClaimViewModel()
            {
                Issuer = x.Issuer,
                Type = x.Type,
                Value = x.Value
            }).ToList();

            return View(userClaimList);
        }

        //[Authorize(Policy = "AnkaraPolicy")]
        [Authorize(Policy = "CityPolicy")]
        [HttpGet]
        public IActionResult AnkaraPage()
        {
            return View();
        }

        [Authorize(Policy = "ExchangePolicy")]
        [HttpGet]
        public IActionResult ExchangePage()
        {
            return View();
        }

        [Authorize(Policy = "ViolencePolicy")]
        [HttpGet]
        public IActionResult ViolencePage()
        {
            return View();
        }
    }
}

NetCoreIdentity/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace NetCoreIdentity.Controllers
{
    public class OrderController : Controller
    {
        [Authorize(Policy = "PermissionsOrderRead")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

NetCoreIdentity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetCoreIdentity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetCoreIdentity.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NetCoreIdentity</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="AnkaraPage">Claim City Policy Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="ExchangePage">Exchange Policy Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="ViolencePage">Violence Policy Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Order Page(Permission)</a>
                        </li>
                    </ul>
                    
                    @* Partial View if your partialView in same file you can use this code.*@
                    <partial name="_NavbarLogin"></partial>
                    @* Partial View if your partialView is not same file you can use this code=> <partial name="PartialViews/_NavbarLogin.cshtml"></partial>*@
                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NetCoreIdentity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NetCoreIdentity/Views/Shared/_NavbarLogin.cshtml
@using System.Security.Claims;
@if (User.Identity!.IsAuthenticated)
{
    <ul class="navbar-nav me-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                @User.Identity.Name
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item" asp-route-returnurl="/Home/Index" asp-controller="Member" asp-action="Index">Profile</a></li>
                <li><a class="dropdown-item" asp-route-returnurl="/Home/Index" asp-controller="Member" asp-action="UserEdit">Update Profile</a></li>
                @if (User.HasClaim(x => x.Type == ClaimTypes.Role && x.Value == "Admin"))
                {
                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Home" asp-action="Index">Admin Page</a></li>
                }
                <li><a class="dropdown-item" asp-controller="Member" asp-action="Claims">Claims</a></li>
                <li><a class="dropdown-item" asp-route-returnurl="/Home/Index" asp-controller="Member" asp-action="PasswordChange">Change Password</a></li>
                <li><a class="dropdown-item" asp-route-returnurl="/Home/Index" asp-controller="Member" asp-action="Logout">Log Out</a></li>
                @* asp-rout-returnurl="/Home/Index" this part adding for alternative logout in MemberController *@
            </ul>
        </li>
    </ul>
}
else
{
    <a class="btn btn-outline-success mx-2" asp-controller="Home" asp-action="SignIn">Sign In</a>
    <a class="btn btn-outline-success" asp-controller="Home" asp-action="SignUp">Sign Up</a>
}